export {default as HeroBG} from './HeroBG.png'
export {default as Tableau} from './Tableau.png'
export {default as download} from './download.png'
export {default as RLogo} from './RLogo.png'
export {default as Amazonwebservices} from './Amazonwebservices.avif'
export {default as MySQL} from './MySQL.png'
export {default as Python} from './Python.png'